### ISSUE TITLE
Avoid deployment if another deployment is in progress

### ISSUE THREAD

**Issue by zetxek** [CircleCI-Public/aws-code-deploy-orb#3]
**Is your feature request related to a problem? Please describe.**

When starting a new deployment in a CodeDeploy application, it always fails if there's already a deployment running.

The orb should skip the build, not fail.

**Describe the solution you'd like**

Skip the build, or offer an option to stop the current one and jump straight away to the new one.

**Describe alternatives you've considered**

Looking for forks of this repo to find somebody that provides the feature - but I'd rather stick to the officially supported orbs.

**Additional context**

This was tested with EC2 autoscaling target groups, with 1 or 2 instances.

**Comment by zetxek** [comment]
If somebody reaches this issue - CircleCI support suggested to implement a deployments Queue via https://circleci.com/orbs/registry/orb/eddiewebb/queue, and it worked as a charm.

Ideally this orb itself can manage - but this is a good and working workaround.

**Comment by brivu** [comment]
Hey @zetxek, 

Since the `queue` orb is a viable solution, I'm going to close this out for now. Please feel free to reopen this ticket if this is still an issue.

Best, 
Brian
