### ISSUE TITLE
SSL Certificate error?

### ISSUE THREAD

**Issue by enricoberti** [CircleCI-Public/aws-code-deploy-orb#31]
**Orb Version**
2.0.0

**Describe the bug**
A few of ours projects at VanMoof use this orb to deploy to AWS. In the deployment job, we also have a step to notify the team via a Slack webhook whether the deployment was successful or not. Slack has recently updated their SSL certificates and we now have a consistent error that there's a problem with the SSL certificate when calling the Slack URL (error 60, SSL certificate problem: certificate has expired).

We also connected to Circle via SSH, trying manually a `curl` to the Slack API url, and get the same. What we noticed is that for the `aws-code-deploy/deploy` job of our pipeline the container that gets used is the unsupported `circleci/python:2.7-stretch` instead of the `cimg/python` one. To double check, we ran the same `curl` command via ssh in a separate container running with `cimg/python` and we have no SSL problem.

**To Reproduce**
Try to curl any https:// url from the container where the deploy job occurs 

**Additional context**
Thanks for the awesome work!

**Comment by brivu** [comment]
Hey @enricoberti, 

Thanks for opening this issue. We're working on a new major release and I went ahead and changed the default executor to the `cimg/aws:2023.03` image. This image comes pre-installed with everything necessary to run any `aws` job successfully. 

We're looking to cut a new release soon. Thanks again! 

-Brian

**Comment by enricoberti** [comment]
excellent, thank you very much for the support!
