### ISSUE TITLE
Allow passing Docker Hub credentials

### ISSUE THREAD

**Issue by mplough-kobold** [CircleCI-Public/aws-code-deploy-orb#8]
## What would you like to be added

Similar to CircleCI-Public/aws-cli-orb#56, we'll need a way to pass the `auth` block to the `docker` configuration parameter ([docs](https://circleci.com/docs/2.0/configuration-reference/#docker)).

## Why is this needed

Starting November 1, 2020, DockerHub will [begin rate-limiting image pulls from DockerHub](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). Users need a way to pass their DockerHub credentials to avoid the rate limit. Without providing this configuration option, deployments from CircleCI will be impacted.

The [Docker Hub Authentication With Orb Executors](https://support.circleci.com/hc/en-us/articles/360051099071-Docker-Hub-Authentication-With-Orb-Executors) article directs customers to raise this kind of issue directly in GitHub repositories.

**Comment by gmemstr** [comment]
CircleCI has partnered with Docker Hub and will not be subject to rate limiting - you can read more here: https://support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ

**Comment by mplough-kobold** [comment]
Thanks for the update, @gmemstr! That makes everything easier.
