### ISSUE TITLE
Pick specific zip file rather than bundle key zip file

### ISSUE THREAD

**Issue by darshan-sixberries** [CircleCI-Public/aws-code-deploy-orb#9]
**Feature request related to a problem with the zip file**
In the circleci file, I have passed the commands to build and zip the dist/build folder and another command to push the zip file to my S3 bucket. but when the was codedeploy workflow starts it creates another zip file containing the whole code and that zip file is picked by codedeploy to deploy on the instance rather than the zip push by the circleci file to S3.

**expected solution**
Is there any way I can tell codedeploy to pick the zip folder pushed by me and not the one which is created by its workflow?

**Comment by brivu** [comment]
Hey @darshan-sixberries, 

When you run the `aws-code-deploy/push` command, it automatically zips up your app's scripts and AppSpec file and uploads it to `aws s3`. 

From my research, the only way for you to deploy your own zip file is by uploading it into `s3` yourself and use the `aws-code-deploy/deploy` command with all the correct parameters to deploy your app. 

According to the `[AWS` Documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/deploy/push.html) for the `aws deploy push` command there isn't a flag that lets you push a file that's already been zipped. 

Hope that helps!

Best, 
Brian
